S_cart/S_cart/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using S_cart.Models;
using S_cart.DB;
using System.Diagnostics;
using System.Text.RegularExpressions;

using System.Text;
using System.Security.Cryptography;

namespace S_cart.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Login(string Username, string Password)
        {
            //Check if username is null
            if (Username == null)
                return View();

            string hashpwd = MD5Hash(Password);
            Debug.WriteLine(hashpwd);

            //Successful login by user
            //Call database (UserData.cs)
            User user = UserData.GetUserByUsername(Username);
            // User not found in database so is null
            if (user == null)
            {
                return View();
            }
            if (user.Password != hashpwd)
                return View();  //Login screen(Index)
            Debug.WriteLine(user.Id);
            Debug.WriteLine(user.Username);
            //Start new session
            string sessionId = SessionData.CreateSession(user.Id);
            return RedirectToAction("Search", "Gallery", new {ses_id = sessionId, fname = user.FirstName,lname=user.LastName, uid=user.Id});
        }

        [HttpPost]     
        public JsonResult IsChecked(string Username)
        {
            if (Regex.IsMatch(Username.ToString(), "^[a-zA-Z0-9]+$"))
                return Json(true);
            return Json(false);
        }

        public static string MD5Hash(string password)
        {
            MD5 md5 = new MD5CryptoServiceProvider();

            //compute hash from the bytes of text  
            md5.ComputeHash(ASCIIEncoding.ASCII.GetBytes(password));

            //get hash result after compute it  
            byte[] result = md5.Hash;

            StringBuilder strBuilder = new StringBuilder();
            for (int i = 0; i < result.Length; i++)
            {
                //change it into 2 hexadecimal digits  
                //for each byte  
                strBuilder.Append(result[i].ToString("x2"));
            }

            return strBuilder.ToString();
        }
    }
}

S_cart/S_cart/Controllers/MyPurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using S_cart.Models;
using S_cart.DB;


namespace S_cart.Controllers
{
    public class MyPurchasesController : Controller
    {
        // GET: MyPurchases
        public ActionResult MyPurchases()
        {
            // Find session id here
            //Storing query result in purchase1
            List<Purchase> purchase1 = PurchaseData.purchasesdb();
            //Storing key-value pair with key as "list", value as purchase1
            //This is to use inside MyPurchases.cshtml 
            ViewData["list"] = purchase1;

            return View();
        }

        public ActionResult ManageActivation()
        {
            // Code for manage activation codes method
            return View();
        }
    }
}   
   

S_cart/S_cart/Views/Shared/General.cshtml
@using S_cart.Models;

@{
    ViewBag.Title = "General";
    User user = (User)ViewData["user"];
}

<h2>The .NET Shop </h2>

@{ 
    <table>
        <tr>
            <th>Hello @user.LastName @user.LastName </th>
        </tr>
    </table>
}

S_cart/S_cart/Views/Shared/_Layout.cshtml
@using S_cart.Models;

@{
    
    string u1 = (string)ViewData["user"];
    int userid = (int)ViewData["uid"];
    int cart_count = (int)ViewData["count"];
}

<!DOCTYPE html>
<html>
<head>
    <link rel=stylesheet href="~/Content/Judy.css" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

</head>

<body>
    @{
        <ul>
            <li><a href="#">The .NET Shop</a></li>
            <li>@Html.ActionLink("Logout", "Login", "Login")</li>
            <li>@Html.ActionLink("My Purchases", "MyPurchases", "MyPurchases")</li>
            <li>
                <a href="@Url.Action("ViewCart", "ViewCart", new { u_id = userid , user_name = u1})">
                    <img alt="View Cart" src="@Url.Content("~/Images/shopping_cart_PNG4.png")" height="25">
                    <span>
                        <input type="text" size="1" name="quantity" style="font-family: Verdana;
                                        font-weight:bold;
                                        font-size:16px;
                                        color:white;
                                        background:#117A65;
                                        border:none"
                               id="quantity" value="@cart_count" />
                    </span>
                </a>
            </li>
        </ul>

    }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - The .NET Shop</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>

S_cart/S_cart/Views/Shared/_LayoutforLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel=stylesheet href="~/Content/Judy.css" />

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

</head>

<body>
    <ul>
        <li><a href="#">The .NET Shop</a></li>
    </ul>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - The .NET Shop</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

S_cart/S_cart/Views/Shared/_greeting.cshtml
@{
    ViewBag.Title = "_greeting";
}


<body>
    <table border="0" width="100%"> <tr> <td align="left" style="background-color:#7CC6B8; color:black; padding-left: 20px"> Welcome, @Model  </td> </tr> </table>
</body>